version: "3.8"

services:
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - REDIS_PORT_NUMBER=6379
    volumes:
      - './redis:/data'

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "15432:80"
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=test@test.test
      - PGADMIN_DEFAULT_PASSWORD=test
    depends_on:
      - db

  prodoctorov:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - pg_admin
